-- ============================================
-- Pricing Engine — Supabase SQL Setup
-- Run this in Supabase SQL Editor
-- ============================================

-- 1. Price Tiers table
create table if not exists price_tiers (
  id bigint generated by default as identity primary key,
  min_price numeric not null check (min_price >= 0),
  max_price numeric check (max_price is null or max_price >= min_price),
  markup numeric not null check (markup > 0),
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. Audit log table
create table if not exists price_tier_audit_log (
  id bigint generated by default as identity primary key,
  tier_id bigint references price_tiers(id) on delete set null,
  action text not null check (action in ('create', 'update', 'delete', 'toggle')),
  old_data jsonb,
  new_data jsonb,
  changed_by text not null default 'system',
  changed_at timestamptz not null default now()
);

-- 3. Function: calculate selling price
create or replace function calculate_selling_price(p_supplier_price numeric)
returns numeric
language plpgsql
stable
as $$
declare
  v_markup numeric;
  v_selling_price numeric;
begin
  select markup into v_markup
  from price_tiers
  where is_active = true
    and p_supplier_price >= min_price
    and (max_price is null or p_supplier_price <= max_price)
  order by sort_order
  limit 1;

  if v_markup is null then
    v_markup := 0;
  end if;

  v_selling_price := p_supplier_price + v_markup;

  if v_selling_price < p_supplier_price then
    v_selling_price := p_supplier_price;
  end if;

  return v_selling_price;
end;
$$;

-- 4. Trigger: auto-update updated_at
create or replace function update_price_tier_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_price_tier_timestamp
  before update on price_tiers
  for each row
  execute function update_price_tier_timestamp();

-- 5. Index for fast lookup
create index if not exists idx_price_tiers_active_sort
  on price_tiers(is_active, sort_order);

-- 6. Enable Row Level Security
alter table price_tiers enable row level security;
alter table price_tier_audit_log enable row level security;

-- Allow all authenticated users to read
create policy "Anyone can read price_tiers"
  on price_tiers for select
  using (true);

-- Only admins can write
create policy "Admins can insert price_tiers"
  on price_tiers for insert
  with check (auth.email() = 'bodash270@gmail.com');

create policy "Admins can update price_tiers"
  on price_tiers for update
  using (auth.email() = 'bodash270@gmail.com');

create policy "Admins can delete price_tiers"
  on price_tiers for delete
  using (auth.email() = 'bodash270@gmail.com');

-- Anyone can read audit log, only admins can write
create policy "Anyone can read audit_log"
  on price_tier_audit_log for select
  using (true);

create policy "Admins can insert audit_log"
  on price_tier_audit_log for insert
  with check (auth.email() = 'bodash270@gmail.com');

-- 7. Insert default tiers (run once)
insert into price_tiers (min_price, max_price, markup, sort_order, is_active) values
  (1,    180,    70,  1, true),
  (181,  600,    134, 2, true),
  (601,  1400,   184, 3, true),
  (1401, 5000,   262, 4, true),
  (5001, 10000,  444, 5, true),
  (10001, null,  987, 6, true)
on conflict do nothing;
